USE [master]
GO

/****** Object:  Database [JobHub]    Script Date: 9/12/2024 12:39:30 PM ******/
CREATE DATABASE [JobHub]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'JobHub', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\JobHub.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'JobHub_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\JobHub_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [JobHub].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [JobHub] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [JobHub] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [JobHub] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [JobHub] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [JobHub] SET ARITHABORT OFF 
GO

ALTER DATABASE [JobHub] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [JobHub] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [JobHub] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [JobHub] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [JobHub] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [JobHub] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [JobHub] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [JobHub] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [JobHub] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [JobHub] SET  ENABLE_BROKER 
GO

ALTER DATABASE [JobHub] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [JobHub] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [JobHub] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [JobHub] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [JobHub] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [JobHub] SET READ_COMMITTED_SNAPSHOT ON 
GO

ALTER DATABASE [JobHub] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [JobHub] SET RECOVERY FULL 
GO

ALTER DATABASE [JobHub] SET  MULTI_USER 
GO

ALTER DATABASE [JobHub] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [JobHub] SET DB_CHAINING OFF 
GO

ALTER DATABASE [JobHub] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [JobHub] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [JobHub] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [JobHub] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [JobHub] SET QUERY_STORE = ON
GO

ALTER DATABASE [JobHub] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [JobHub] SET  READ_WRITE 
GO


